### ISSUE TITLE
One time recordings

### ISSUE THREAD

**Issue by camster91** [pkscout/script.tvmaze.integration#1]
Hello! Thanks so much for your work on TVMaze Integration. I got it working well on my system.

I'm wondering if it wouldn't be too much trouble to set up one time recordings instead of reoccurring? 

I find a lot of shows come and go randomly skipping weeks or going on mid season breaks. I prefer to not have a lot of repeat recordings or recordings of other shows by mistake.

I would like the script to run every day, check my guide and schedule the shows for that day only. Next week the show might not be on and then it will skip over the show.

Would you be able to help me with this? I'll look at the code to see if I can figure it out too

Thanks!

**Comment by pkscout** [comment]
I feel like you're trying to reinvent recurring recordings.  The thing you are trying to avoid (repeat recordings or recordings of other shows by mistake) is exactly what you will get if you try and schedule recordings once a day. You could get a rerun of a show (because the record once function doesn't keep any history), or a show with the same name that isn't really your show (like Magnum P.I. which has two versions).  You can certainly go down this path if you want to, but after this post I'm closing the issue and won't assist anymore.  If you are having problems with recordings not working the way you expect, you should really post something to the NextPVR forum.

Anyway, if you look in `resources/lib/apis/nextpvr.py` you'll find a function called `scheduleNewRecurringRecording`. In that function change `params['method'] = 'recording.recurring.save'` to `params['method'] = 'recording.save'`.  If you are using a TVMaze tag to identify which shows to try and record, you also need add `tvmaze_untag=False` to your settings.py file so that the script will keep checking for the shows you've tagged.
